# Generated by Django 2.0.5 on 2018-06-13 10:43

from django.db import migrations
import django_ipam.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_ipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='subnet',
            field=django_ipam.base.fields.NetworkField(db_index=True, help_text='Subnet in CIDR notation, eg: "10.0.0.0/24" for IPv4 and "fdb6:21b:a477::9f7/64" for IPv6', max_length=43),
        ),
    ]
