# Generated by Django 2.0.5 on 2018-06-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ipam', '0002_auto_20180613_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='owner',
        ),
    ]
